### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by mortensassi** [Gimenz/insta-fetcher#1]
Getting a CORS error when trying your example. Seems like Insta blocked this

**Comment by Gimenz** [comment]
Yep, my best solution is using sessionid
Wanna to contribute to fix it?

**Comment by mortensassi** [comment]
Sorry i don't know how to fix this

**Comment by Sennar4** [comment]
@mortensassi 
It is not that hard actually. For me it worked when using it on my feather.js server instead of my client.
Gruß nach Düsseldorf

**Comment by mortensassi** [comment]
@Sennar4 thanks for your reply. But wouldn't Instagram block your servers IP with time? That was my main problem with php scraping. What did you actually write for your server? Are you using this plugin and output the data in your API?
Cheers und grüße zurück!
