### ISSUE TITLE
Axios error 

### ISSUE THREAD

**Issue by etepes** [Gimenz/insta-fetcher#10]
Request failed with status code 400
Having this issue for 2 weeks

Version: 1.3.21

**Comment by Gimenz** [comment]
i think it requires email / phone verification.

**Comment by etepes** [comment]
> i think it requires email / phone verification.

Maybe but, will nothing happen if I use my personal account to download videos/photos from instagram? Maybe they will ban my account or suspend it for some time idk

**Comment by Gimenz** [comment]
yes maybe, but i never got banned so far

**Comment by etepes** [comment]
> yes maybe, but i never got banned so far

I tried with my main account and still doesn't work and getSessionId doesn't work either, it shows axios error 400
