### ISSUE TITLE
Video Type Media Does not return video_url

### ISSUE THREAD

**Issue by harsh253** [Gimenz/insta-fetcher#11]
Adding a sample node json response where 'is_video' : true but it does not have a video_url as stated in the docs. I see that it is an optional key so wanted to understand if only few kind of videos return a video_url

![image](https://user-images.githubusercontent.com/32335320/172696007-54a9e9b6-03aa-4224-b5f8-271878b3b53a.png)

**Comment by Gimenz** [comment]
i never think about it, but if you want to do PR, it could be better

**Comment by harsh253** [comment]
The response types that are defined in the source code, where do we get those from ? Are we getting it from the official instagram api docs or building on our own through responses ?

**Comment by harsh253** [comment]
It looks like the Graphql api to `fetchUserPosts` is updated to use 2 query parameters as opposed to 1 - 
Currently we have
`params = {
'query_id': '17880160963012870',
			'id': userId,
			'first': 12,
			'after': end_cursor
}`

After updating to the following, I am getting `video_url` in the response along with all other properties mentioned in `PurpleNode`
`'query_hash' : '69cba40317214236af40e7efa697781d',
			'variables' : {
				"id" : userId,
				"first" : 12,
				"after": end_cursor
			}`
			
The response now looks like the following - 

![image](https://user-images.githubusercontent.com/32335320/173221527-1555b228-3621-4c83-9dba-091518af71e8.png)


Will raise a PR for this soon

**Comment by harsh253** [comment]
PR associated with this fix

> https://github.com/Gimenz/insta-fetcher/pull/12

**Comment by Gimenz** [comment]
ah thanks, you made this module more be better. sorry my code too dirty, because this my first project for learning typescript.

**Comment by harsh253** [comment]
Ah. In fact I'm also a beginner at typescript. Let's build this module even better. 
Can you please review and merge the PR too ?

**Comment by Gimenz** [comment]
Maaf, saya terlalu sibuk di dunia nyata akhir-akhir ini, jadi saya belum sempat membuka komputer

**Comment by harsh253** [comment]
Cool. Could you please update the npm version as well with latest code ? 

PR https://github.com/Gimenz/insta-fetcher/pull/12 fixes this issue

**Comment by Gimenz** [comment]
sure, but i will fixing some bug first,  you needed it urgently, install from github. thanks
