### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by jacktheboss220** [Gimenz/insta-fetcher#14]
Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded

getting this message after using featchPost funtion

pls help.

**Comment by Rippanteq7** [comment]
Same issue

**Comment by jacktheboss220** [comment]
?__a=1&__d=dis this may help

**Comment by Gimenz** [comment]
try now, i've published to npm
