### ISSUE TITLE
I Think Instagram Has Changed Session ID Format, Its Way Too Big Now!

### ISSUE THREAD

**Issue by yadavdotcodes** [Gimenz/insta-fetcher#15]
Also Login Doesn't Work Via New Session Id For Your Package!

![image](https://user-images.githubusercontent.com/90105839/176602782-873d073d-1807-411f-bce9-0d615cbfcf0f.png)

**Comment by Gimenz** [comment]
have you try it to use with many function?

**Comment by yadavdotcodes** [comment]
What Is Many Function, Example?

**Comment by jacktheboss220** [comment]
> Also Login Doesn't Work Via New Session Id For Your Package!
> 
> ![image](https://user-images.githubusercontent.com/90105839/176602782-873d073d-1807-411f-bce9-0d615cbfcf0f.png)

same while tring to get session_id

**Comment by yadavdotcodes** [comment]
@Gimenz Update:- I Tried To Login Via Different Account (Personal) & Same Thing Happened!

**Comment by Gimenz** [comment]
i've update the session id format, into full of cookie. try it

**Comment by yadavdotcodes** [comment]
Still Same :(, Also This Long Cookie Isn't Working With Your Library! SS Below 👇🏻

![image](https://user-images.githubusercontent.com/90105839/176897760-4dd6bb9b-56cf-4546-ae9b-a7a5024d51bb.png)

If I Try To Fetch Post With This Session ID, This Happens 👇🏻

![image](https://user-images.githubusercontent.com/90105839/176898398-de5dfe6c-5f5f-4eb7-b3fc-f38a93bd4984.png)

**Comment by jacktheboss220** [comment]
> Still Same :(, Also This Long Cookie Isn't Working With Your Library! SS Below 👇🏻
> 
> ![image](https://user-images.githubusercontent.com/90105839/176897760-4dd6bb9b-56cf-4546-ae9b-a7a5024d51bb.png)
> 
> If I Try To Fetch Post With This Session ID, This Happens 👇🏻
> 
> ![image](https://user-images.githubusercontent.com/90105839/176898398-de5dfe6c-5f5f-4eb7-b3fc-f38a93bd4984.png)
> 
> Also Web Cookies Are Longer Now!
> 
> ![image](https://user-images.githubusercontent.com/90105839/176899787-1c047593-7e8d-423e-9c42-d67118811594.png)

getting same error
any fix?

**Comment by Gimenz** [comment]
ah sorry, i forgot to write new example, just copy all cookies that returned from getSessionId. maybe instagram has made changes, i try to use full of cookie, not just sessionid.

**Comment by yadavdotcodes** [comment]
Ok, Write New Examples & Drop A Link! :)
I Already Have Full Cookies!

**Comment by yadavdotcodes** [comment]
> > ah sorry, i forgot to write new example, just copy all cookies that returned from getSessionId. maybe instagram has made changes, i try to use full of cookie, not just sessionid.
> 
> thnx worked :)

How Worked?, Mine Not Working!

**Comment by jacktheboss220** [comment]
> > > ah sorry, i forgot to write new example, just copy all cookies that returned from getSessionId. maybe instagram has made changes, i try to use full of cookie, not just sessionid.
> > 
> > 
> > thnx worked :)
> 
> How Worked?, Mine Not Working!

remove 'encodeURIComponent' from session.js
 then run copy all.

**Comment by Gimenz** [comment]
can you show ig password here? just password, i want know is the password contains special character.
> remove 'encodeURIComponent' from session.js line 67 then run copy all.

**Comment by jacktheboss220** [comment]
> can you show ig password here? just password, i want know is the password contains special character.
> 
> > remove 'encodeURIComponent' from session.js line 67 then run copy all.

yes i contain '@'

**Comment by yadavdotcodes** [comment]
> can you show ig password here? just password, i want know is the password contains special character.
> 
> > remove 'encodeURIComponent' from session.js line 67 then run copy all.

Mine Also Contains @ And #

**Comment by Gimenz** [comment]
> yes it contain '@'

i use encodeURI bcz i think it can solve the problem, my password contains three dots ...
could i remove it?

**Comment by yadavdotcodes** [comment]
> > yes it contain '@'
> 
> i use encodeURI bcz i think it can solve the problem, my password contains three dots ... could i remove it?

Yes, Its Causing Problem!

**Comment by jacktheboss220** [comment]
> > yes it contain '@'
> 
> i use encodeURI bcz i think it can solve the problem, my password contains three dots ... could i remove it?

try using without encodeURI, it may work fine.

**Comment by yadavdotcodes** [comment]
![image](https://user-images.githubusercontent.com/90105839/176927221-c3593d73-42c6-4927-bb7e-79d174dc34f4.png)

**Comment by yadavdotcodes** [comment]
Should I Send You My Username Password?, We Can Talk On Telegram If You Have!

**Comment by Gimenz** [comment]
hmmm, are you using old constructor method? 

![image](https://user-images.githubusercontent.com/23699593/176928067-8aa891b0-f56d-45e0-a106-d79b4d6d46fb.png)

**Comment by yadavdotcodes** [comment]
> hmmm, are you using old constructor method?
> 
> ![image](https://user-images.githubusercontent.com/23699593/176928067-8aa891b0-f56d-45e0-a106-d79b4d6d46fb.png)

Yes! Ofcourse!, Is There New?

**Comment by yadavdotcodes** [comment]
> hahaha, i think you've used the new method.
> 
> i was said here, copy all cookies, try it!
> 
> > ah sorry, i forgot to write new example, just copy all cookies that returned from getSessionId. maybe instagram has made changes, i try to use full of cookie, not just sessionid.

Can't Understand! Please Quote A Example 🙄

**Comment by yadavdotcodes** [comment]
Thanks!, Now Working!

**Comment by Gimenz** [comment]
sorry my bad english :D

may this can help you
![image](https://user-images.githubusercontent.com/23699593/176929047-dff4f0c6-7743-46f3-ac77-9283577e9255.png)

**Comment by jacktheboss220** [comment]
> So I Removed `encodeURIComponent` But Still Same Issue @jacktheboss220, Can We Talk On Instagram?
> 
> ![image](https://user-images.githubusercontent.com/90105839/176925682-17ab0768-4ff5-4007-bdb0-89b7e46bea7d.png)

just copy all session_id

**Comment by jacktheboss220** [comment]
> sorry my bad english :D
> 
> may this can help you ![image](https://user-images.githubusercontent.com/23699593/176929047-dff4f0c6-7743-46f3-ac77-9283577e9255.png)

can you make these changes in npm .

**Comment by yadavdotcodes** [comment]
Done!!!!!, Thanks For Your Library!

**Comment by Gimenz** [comment]
changes for what? can you explain here?

> > sorry my bad english :D
> > may this can help you ![image](https://user-images.githubusercontent.com/23699593/176929047-dff4f0c6-7743-46f3-ac77-9283577e9255.png)
> 
> can you make these changes in npm .
> 
> it will be easy to get from npm without editing from my side. ;) thnx for the help

**Comment by jacktheboss220** [comment]
> changes for what? can you explain here?
> 
> > > sorry my bad english :D
> > > may this can help you ![image](https://user-images.githubusercontent.com/23699593/176929047-dff4f0c6-7743-46f3-ac77-9283577e9255.png)
> > 
> > 
> > can you make these changes in npm .
> > it will be easy to get from npm without editing from my side. ;) thnx for the help

removing the 'encodeURIComponent'

**Comment by Gimenz** [comment]
oh yep, just wait. 
> removing the 'encodeURIComponent'

**Comment by jacktheboss220** [comment]
> oh yep, just wait.
> 
> > removing the 'encodeURIComponent'

thnx. 
:) 😊

**Comment by Gimenz** [comment]
Hi @jacktheboss220 , i've removed the `encodeURIComponent` at `getSessionId()` function, but i made other function `getCookie()` that using encodeURIComponent. because i think if the password contains special character it causing Request Error 400 Bad Request.

Thanks.

**Comment by yadavdotcodes** [comment]
@Gimenz I Am Creating A Simailar Library As insta-fetcher, So A Question, How Do I Get app-id?

**Comment by Gimenz** [comment]
app-id for what?

**Comment by yadavdotcodes** [comment]
![image](https://user-images.githubusercontent.com/90105839/177919216-7a189238-277b-499c-8a18-45039cd598bd.png)
This One, Or Its Same For Everyone?
