### ISSUE TITLE
Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)

### ISSUE THREAD

**Issue by otopba** [Gimenz/insta-fetcher#17]
Hello!

After upgrading `insta-fetcher` to `^1.3.22` I started getting the following error:

```
 Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
```

when calling the `getSessionId` function

**Comment by Gimenz** [comment]
check your connection

**Comment by otopba** [comment]
@Gimenz Oh you are right. Thank you!
