### ISSUE TITLE
image not downloading its opening in new tag

### ISSUE THREAD

**Issue by umeshinde007** [Gimenz/insta-fetcher#18]
hello ..i put image link to anchor tag since i want to download image but instead od downlaoding its opeing in new tag..how to get rid of this ?

**Comment by Gimenz** [comment]
what do you mean?

**Comment by umeshinde007** [comment]
i mean this is  link im using anovhr tag so on button click i want to download this image
https://instagram.fpnq2-1.fna.fbcdn.net/v/t51.2885-15/290931451_1163554797777049_6282555034754137941_n.webp?stp=dst-jpg_e35&_nc_ht=instagram.fpnq2-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=5PsjyvwHnlUAX--Rdxk&edm=AABBvjUBAAAA&ccb=7-5&ig_cache_key=Mjg3MjgwMjUzNzIwMTIwMjI2Ng%3D%3D.2-ccb7-5&oh=00_AT8DUvkax5WpccbMMMSQp-KgVGGfREUODtYn9ZMmfa8CqQ&oe=62C5410C&_nc_sid=83d603


but its opening in new tab how to et rid of this

**Comment by Gimenz** [comment]
new tab?? i think you asked the question that out of the topic of this library. sorry idk about it.
