### ISSUE TITLE
TypeError: Cannot read property 'shortcode_media' of undefined

### ISSUE THREAD

**Issue by TheGreatLebowski** [Gimenz/insta-fetcher#2]
Hi,

When I'm trying your FetchPost exemple, I have the following error : 
TypeError : `Cannot read property 'shortcode_media' of undefined`

And if I am trying FetchUser : 
TypeError : `Cannot read property 'user' of undefined` (Line 112 of index.js)

Do I need a sessionId so it will works ?

**Comment by Gimenz** [comment]
yes, by using sessionId, it will work
