### ISSUE TITLE
bingung

### ISSUE THREAD

**Issue by thoriqazzikraa** [Gimenz/insta-fetcher#26]
ini cara make proxy gmna dah bang
mksd gw url proxy nya ini nyari dimana

**Comment by Gimenz** [comment]
bisa pake free proxy list, tp blm nyoba.

**Comment by Gimenz** [comment]
coba pake cara ini https://masteringjs.io/tutorials/axios/proxy

**Comment by thoriqazzikraa** [comment]
> coba pake cara ini https://masteringjs.io/tutorials/axios/proxy

request failed with status code 500

**Comment by Gimenz** [comment]
berarti proxy nya, cari yang bagus coba

**Comment by thoriqazzikraa** [comment]
> berarti proxy nya, cari yang bagus coba

bisa bang tdi, ngakalin yg abg kasi link 
![Screenshot_2022-10-26-06-16-11-68](https://user-images.githubusercontent.com/89589243/197900300-892bdd50-6fcc-4cda-adca-831e5acebfdb.jpg)

**Comment by thoriqazzikraa** [comment]
> berarti proxy nya, cari yang bagus coba

btw bg
fetchStories error

**Comment by Gimenz** [comment]
aman kok

![0ABEE72A-BC51-40AA-9CCB-E1E8453B8171](https://user-images.githubusercontent.com/23699593/197922661-b211bb25-2d4b-44de-b561-b42d71488fd3.png)

**Comment by thoriqazzikraa** [comment]
> aman kok
> 
> ![0ABEE72A-BC51-40AA-9CCB-E1E8453B8171](https://user-images.githubusercontent.com/23699593/197922661-b211bb25-2d4b-44de-b561-b42d71488fd3.png)

lah, dh dignti jadi make url kah?
kemaren make username bisa skrng gabisa

**Comment by thoriqazzikraa** [comment]
dah nyoba eval returnnya request failed with status code 404

**Comment by thoriqazzikraa** [comment]
![Uploading Screenshot_2022-10-26-11-31-46-59_375f2148cf8fa4d7b3a7c6a3ff0c7e6c.jpg…]()

**Comment by thoriqazzikraa** [comment]
![Screenshot_2022-10-26-11-31-46-59_375f2148cf8fa4d7b3a7c6a3ff0c7e6c](https://user-images.githubusercontent.com/89589243/197935196-1cfadf3f-28df-4a99-8f32-e7836582328f.jpg)

**Comment by Gimenz** [comment]
itu kamu bikin request sendiri? berarti tidak ada kaitannya dengan repo ini :)

**Comment by thoriqazzikraa** [comment]
> itu kamu bikin request sendiri? berarti tidak ada kaitannya dengan repo ini :)

ngga, itu nyoba ngambil data dari url yg ada di repo ini
di config.json
alhasil null

**Comment by Gimenz** [comment]
aku lihat di screenshot itu nggak pakai library ini, tapi kamu request langsung pake axios

**Comment by thoriqazzikraa** [comment]
> aku lihat di screenshot itu nggak pakai library ini, tapi kamu request langsung pake axios

![IMG_20221027_072537](https://user-images.githubusercontent.com/89589243/198163114-a855ce51-8637-4d03-bec3-4239e77f0a33.jpg)

itu yg make axios cuman nyoba liat data base url yg ada di config.json di repo ini

**Comment by thoriqazzikraa** [comment]
![IMG_20221027_072809](https://user-images.githubusercontent.com/89589243/198163357-e7ac60ad-d2b9-46d9-ace6-cf08e77c9208.jpg)
url yg ini saya coba

**Comment by Gimenz** [comment]
iya tetep aja tidak ada kaitannya dg repo ini, kan itu make axios. bukan pakai repo ini

**Comment by thoriqazzikraa** [comment]
> > aku lihat di screenshot itu nggak pakai library ini, tapi kamu request langsung pake axios
> 
> ![IMG_20221027_072537](https://user-images.githubusercontent.com/89589243/198163114-a855ce51-8637-4d03-bec3-4239e77f0a33.jpg)
> 
> itu yg make axios cuman nyoba liat data base url yg ada di config.json di repo ini

ini bg make module

**Comment by Gimenz** [comment]
nah kalo gitu kan bisa jelas, udah ketemu bug nya, thanks.

**Comment by Gimenz** [comment]
coba sekarang update ke latest / v1.3.25

**Comment by thoriqazzikraa** [comment]
> coba sekarang update ke latest / v1.3.25

dah bisa bang, terima kasihh

**Comment by thoriqazzikraa** [comment]
> coba sekarang update ke latest / v1.3.25

sesi masih suka revoke ya bg
pdhl udh make proxy
```
const httpProxy = require('http-proxy')
const http = require('http')
const express = require('express')
const { igApi } = require('insta-fetcher')
const cookieIg = 'ig_did=C8B73274-F442-4F83-A752-C2AC0BEDCFF0; ig_nrcb=1; mid=Y1hG1wALAAGWplAK3kx8jJxus6X9; datr=60ZYY8cuQe3zPQh_F54rjMmP; ds_user_id=56220214914; csrftoken=I7M4aAdStWkI3W5k46caxpTIPEhclR9K; sessionid=56220214914:u3HvZhXdJ4TBl2:22:AYf7H3soN1ZTrKJy-MGA3lQmAg2SiuiJJSmdF2VlDQ; rur="NAO\05456220214914\0541699091470:01f740e1c7334acacaf42dd12df681ef165e81e25d0fa1bd3d57ce92e6efc8ff98d48d54"'

const proxi = httpProxy.createProxyServer({})
const app = express()
var server = http.createServer(function(req, res) {
	console.log('Request', req.method, req.url)
	proxi.web(req, res, { target: `http//${req.hostname}` })
})
const options = {
	host: 'localhost',
	port: 3000,
	protocol: 'http'
}
const scrapeIg = new igApi(cookieIg, false, { options })
server.listen(3000)

module.exports = { scrapeIg, cookieIg }
```
