### ISSUE TITLE
"instagram.com/USERNAME/?__a=1&__d=dis" returns 404

### ISSUE THREAD

**Issue by wik3d** [Gimenz/insta-fetcher#32]
When requesting an instagram account with the payload: '?__a=1&__d=dis', now returns a 404 page not found. This is used within multiple methods, for example the getIdByUsername() method

![image](https://github.com/Gimenz/insta-fetcher/assets/61479652/45f1f5f0-1726-43c9-a63e-7095b820cac1)

![image](https://github.com/Gimenz/insta-fetcher/assets/61479652/a7438e35-a57c-4937-87b6-bc9ed2661fc0)

When requesting this URL from a browser. It also returns 404.

![image](https://github.com/Gimenz/insta-fetcher/assets/61479652/af15340c-0231-473f-8546-e2a6b30e6560)

I'm not sure of a workaround to this yet, if you know anything let me know

**Comment by jfrenl** [comment]
Yeah i am afraid that there is no other endpoint for scraping this data. The main endpoint of instagram is still available but that one has high security sadly. The only parameter i found so far is ?__user=0

**Comment by wik3d** [comment]
> Yeah i am afraid that there is no other endpoint for scraping this data. The main endpoint of instagram is still available but that one has high security sadly. The only parameter i found so far is ?__user=0

Yeah, I found the main endpoint: _https://i.instagram.com/api/v1/users/web_profile_info/?username=someone_ and I've been using it in combination with high quality proxies. I haven't had a single failed request, although I haven't quite spammed it to stress test, but it appears to be working consistently

**Comment by wik3d** [comment]
Added, .jac.k. Is my user
