### ISSUE TITLE
getSessionId id throws axios error

### ISSUE THREAD

**Issue by amini-reza** [Gimenz/insta-fetcher#5]
![Screen Shot 1400-12-17 at 12 19 01](https://user-images.githubusercontent.com/54965892/157201802-4061e20f-c952-41e7-bb7c-6ec6c5b81025.png)

Let me know what additional data you need.

**Comment by Gimenz** [comment]
ok thanks, i'll update next time, or if you want contribute

**Comment by Gimenz** [comment]
should be fixed as https://github.com/Gimenz/insta-fetcher/commit/8758a59b6e25aac95b0415fc833373cfe97e718c

**Comment by Gimenz** [comment]
hello, have you try it now? are  it working properly?
