### ISSUE TITLE
In How Much Days Cookies Get Expire?

### ISSUE THREAD

**Issue by icancodebeauty** [Gimenz/insta-fetcher#8]
In How Much Days Cookies Get Expire?, Becoz `insta-fetcher` Requires New `session-id` Everyday!, I Am Lil Bit Confused About That Why It Shows!

**Comment by Gimenz** [comment]
hi, i was use this library for my downloader bot, i never update the session-id, only if i forgot to backup bot file while server going to expired.

did you use it for upload media? i have try to upload post, and my bot user is spamming. then my IG account got checkpoint.

**Comment by icancodebeauty** [comment]
I Am Using It With Express.js To Get My Followers But It EveryDay Wants New Session Id!

**Comment by icancodebeauty** [comment]
Done, Problem Solved
