### ISSUE TITLE
Get all profile posts

### ISSUE THREAD

**Issue by am-monkey** [Gimenz/insta-fetcher#9]
Hey @Gimenz !

Is there a way how to paginate and scrape **all user posts**? For now it gets only 12 posts.

I found `page_info` object and it seems that it can be used for this purposes.
![](https://i.ibb.co/N7HnryS/2022-04-17-15-56-31.png)

Do you have any ideas?

Thanks & Regards,
Ilya

**Comment by Gimenz** [comment]
Hi, thanks for open an issue.

i think by using this https://www.instagram.com/graphql/query/?query_id=17880160963012870&id={userID}&first=100 it can scrape mosts user posts

but for now, idk how to get nextpage posts.
if you can make a pull req, that's great 😃 

reference [InstaPy](https://github.com/InstaPy/instapy-research/blob/0f1fc81b637fe64e2b4a69ff1cde0934006c2ba1/api/API_ENDPOINTS.md)

**Comment by Gimenz** [comment]
hi, i've added function to get all user posts with pagination, test it, see example.ts file for example code
